export const cloudHostingConfig = {

    sectionTitle: "Game Hosting Plans",
    sectionDescription: "High-performance game hosting designed for speed, security, and scalability.",


    currency: "£",


    plans: [
        {
            id: "coal",
            name: "Coal (2GB)",
            price: "2.50",
            originalPrice: "5.00",
            discount: "50%",
            renewalPrice: "2.50",
            theme: "gray",
            isBestValue: false,
            badge: null,
            badgeColor: "bg-gray-500",
            features: [
                "Ryzen 9 9950X CPU",
                "2GB DDR5 RAM",
                "20GB NVMe Storage",
                "10GB Backups Storage",
                "3 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/coal"
        },
        {
            id: "iron",
            name: "Iron (4GB)",
            price: "5.00",
            originalPrice: "10.00",
            discount: "50%",
            renewalPrice: "5.00",
            theme: "orange",
            isBestValue: false,
            badge: null,
            features: [
                "Ryzen 9 9950X CPU",
                "4GB DDR5 RAM",
                "40GB NVMe Storage",
                "20GB Backups Storage",
                "3 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/iron"
        },
        {
            id: "gold",
            name: "Gold (6GB)",
            price: "7.50",
            originalPrice: "15.00",
            discount: "50%",
            renewalPrice: "7.50",
            theme: "amber",
            isBestValue: false,
            badge: null,
            badgeColor: "bg-amber-500",
            features: [
                "Ryzen 9 9950X CPU",
                "6GB DDR5 RAM",
                "60GB NVMe Storage",
                "30GB Backups Storage",
                "3 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/gold"
        },
        {
            id: "lapis",
            name: "Lapis (8GB)",
            price: "10.00",
            originalPrice: "20.00",
            discount: "50%",
            renewalPrice: "10.00",
            theme: "blue",
            isBestValue: false,
            badge: null,
            features: [
                "Ryzen 9 9950X CPU",
                "8GB DDR5 RAM",
                "80GB NVMe Storage",
                "40GB Backups Storage",
                "3 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/lapis"
        },
        {
            id: "diamond",
            name: "Diamond (12GB)",
            price: "15.00",
            originalPrice: "37.50",
            discount: "60%",
            renewalPrice: "15.00",
            theme: "sky",
            isBestValue: false,
            badge: null,
            badgeColor: "bg-sky-500",
            features: [
                "Ryzen 9 9950X CPU",
                "12GB DDR5 RAM",
                "120GB NVMe Storage",
                "60GB Backups Storage",
                "5 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/diamond"
        },
        {
            id: "emerald",
            name: "Emerald (16GB)",
            price: "20.00",
            originalPrice: "50.00",
            discount: "60%",
            renewalPrice: "20.00",
            theme: "emerald",
            isBestValue: false,
            badge: "Best Performance",
            badgeColor: "bg-emerald-500",
            features: [
                "Ryzen 9 9950X CPU",
                "16GB DDR5 RAM",
                "160GB NVMe Storage",
                "80GB Backups Storage",
                "5 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/emerald"
        },
        {
            id: "amethyst",
            name: "Amethyst (24GB)",
            price: "30.00",
            originalPrice: "75.00",
            discount: "60%",
            renewalPrice: "30.00",
            theme: "indigo",
            isBestValue: false,
            badge: null,
            badgeColor: "bg-indigo-500",
            features: [
                "Ryzen 9 9950X CPU",
                "24GB DDR5 RAM",
                "240GB NVMe Storage",
                "120GB Backups Storage",
                "5 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/amethyst"
        },
        {
            id: "beacon",
            name: "Beacon (32GB)",
            price: "40.00",
            originalPrice: "100.00",
            discount: "60%",
            renewalPrice: "40.00",
            theme: "red",
            isBestValue: false,
            badge: null,
            badgeColor: "bg-red-500",
            features: [
                "Ryzen 9 9950X CPU",
                "32GB DDR5 RAM",
                "320GB NVMe Storage",
                "160GB Backups Storage",
                "5 MySQL Databases",
                "Unlimited Player Slots",
                "Supports 15+ Games",
            ],
            link: "https://client.intranex.org/index.php?rp=/store/game-hosting/beacon"
        }
    ]
};
