export const dedicatedServerConfig = {
    currency: "£",
    filterPriceRange: { min: 0, max: 1000 },
    locations: [
        { id: 'uk-ldn', name: 'London, UK', country: 'GB' },
        { id: 'us-nyc', name: 'New York City, US', country: 'US' },
    ],
    cpuTypes: [
        'AMD',
        'Intel'
    ],
    ramRanges: [
        { label: '32GB - 64GB', min: 32, max: 64 },
        { label: '96GB - 128GB', min: 96, max: 128 },
        { label: '192GB - 512GB', min: 192, max: 512 },
        { label: '768GB+', min: 768, max: 2048 },
    ],
    servers: [

        {
            id: 'ds-amd-9',
            cpu: 'AMD Ryzen 7 5800X',
            cores: 8,
            threads: 16,
            type: 'AMD',
            ram: '128GB DDR4',
            storage: '1TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'us-nyc',
            price: 95.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-7-5800x-nyc'
        },
        {
            id: 'ds-amd-1',
            cpu: 'AMD Ryzen 5 5600X',
            cores: 6,
            threads: 12,
            type: 'AMD',
            ram: '32GB DDR4',
            storage: '2x 512GB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'uk-ldn',
            price: 110.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-5-5600x-ldn'
        },
        {
            id: 'ds-amd-2',
            cpu: 'AMD Ryzen 7 3700',
            cores: 8,
            threads: 16,
            type: 'AMD',
            ram: '64GB DDR4',
            storage: '2x 960GB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'uk-ldn',
            price: 115.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-7-3700-ldn'
        },
        {
            id: 'ds-amd-3',
            cpu: 'AMD Ryzen 9 5950X',
            cores: 16,
            threads: 32,
            type: 'AMD',
            ram: '128GB DDR4',
            storage: '2TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'us-nyc',
            price: 120.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-9-5950x-nyc'
        },
        {
            id: 'ds-amd-4',
            cpu: 'AMD Ryzen 7 7700X',
            cores: 8,
            threads: 16,
            type: 'AMD',
            ram: '128GB DDR5',
            storage: '2x 1TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'us-nyc',
            price: 130.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-7-7700x-nyc'
        },
        {
            id: 'ds-amd-5',
            cpu: 'AMD Ryzen 9 3900',
            cores: 12,
            threads: 24,
            type: 'AMD',
            ram: '128GB DDR4',
            storage: '2x 2TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'uk-ldn',
            price: 145.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-9-3900-ldn'
        },
        {
            id: 'ds-amd-6',
            cpu: 'AMD Ryzen 9 7950X',
            cores: 16,
            threads: 32,
            type: 'AMD',
            ram: '192GB DDR5',
            storage: '2x 4TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'us-nyc',
            price: 185.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-9-7950x-nyc'
        },
        {
            id: 'ds-amd-7',
            cpu: 'AMD Ryzen 9 9950X',
            cores: 16,
            threads: 32,
            type: 'AMD',
            ram: '256GB DDR5',
            storage: '2x 4TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'us-nyc',
            price: 250.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-9-9950x-nyc'
        },
        {
            id: 'ds-amd-8',
            cpu: 'AMD Ryzen 9 9950X',
            cores: 16,
            threads: 32,
            type: 'AMD',
            ram: '192GB DDR5',
            storage: '2x 2TB NVMe',
            bandwidth: '1 Gbps Unmetered',
            portSpeed: '1 Gbps',
            location: 'uk-ldn',
            price: 260.00,
            link: 'https://client.intranex.org/index.php?rp=/store/dedicated-servers/amd-ryzen-9-9950x-ldn'
        }
    ]
};
